version: "3"

volumes:
  boruta-logs:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  boruta:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.full
      args:
        BORUTA_OAUTH_BASE_URL: "http://localhost:8080"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - "boruta-logs:/app/log"
    env_file: "./.env.example"
    environment:
      MIX_ENV: "prod"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
      POSTGRES_HOST: "postgres"
    depends_on:
      postgres:
        condition: service_healthy

