---
version: "1.0"
configuration:
  name: kagome-1
  aliases:
    - "kagome.1.docker"
  microgateway:
    - scheme: "http"
      port: 4000
      virtual_host: "kagome-1"
      host: "localhost"
      uris: ["/echo"]
      strip_uri: false
    - scheme: "https"
      port: 8043
      virtual_host: "kagome-1"
      mtls_enabled: true
      host: "kagome-2"
      uris: ["/"]
      strip_uri: false
