---
configuration:
  gateway:
    - scheme: "https"
      mtls_enabled: true
      port: 8044
      host: "kagome-1"
      uris: ["/kagome-1"]
      strip_uri: true
    - scheme: "https"
      mtls_enabled: true
      port: 8044
      host: "kagome-2"
      uris: ["/kagome-2"]
      strip_uri: true
