version: "3"

volumes:
  boruta-logs:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  boruta-server:
    image: ghcr.io/malach-it/boruta-server:master
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "boruta-logs:/app/log"
      - "./config:/app/config"
    env_file: "../../.env.example"
    environment:
      MIX_ENV: "prod"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
      POSTGRES_HOST: "postgres"
      BORUTA_GATEWAY_CONFIGURATION_PATH: "config/example-gateway-configuration.yml"
    depends_on:
      postgres:
        condition: service_healthy

  httpbin-sidecar:
    image: ghcr.io/malach-it/boruta-gateway:master
    volumes:
      - "boruta-logs:/app/log"
      - "./config:/app/config"
    env_file: "../../.env.example"
    environment:
      MIX_ENV: "prod"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
      POSTGRES_HOST: "postgres"
      BORUTA_GATEWAY_CONFIGURATION_PATH: "config/example-httpbin-configuration.yml"
    depends_on:
      postgres:
        condition: service_healthy

  protected-httpbin-sidecar:
    image: ghcr.io/malach-it/boruta-gateway:master
    volumes:
      - "boruta-logs:/app/log"
      - "./config:/app/config"
    env_file: "../../.env.example"
    environment:
      MIX_ENV: "prod"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "boruta_release"
      POSTGRES_HOST: "postgres"
      BORUTA_GATEWAY_CONFIGURATION_PATH: "config/example-protected-httpbin-configuration.yml"
    depends_on:
      postgres:
        condition: service_healthy

  httpbin:
    image: kennethreitz/httpbin
